In [1]:
!pip install torch

In [2]:
import torch

In [5]:
X = torch.arange(20, dtype=torch.float32)
X, X.numel(), X.shape

(tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
         14., 15., 16., 17., 18., 19.]),
 20,
 torch.Size([20]))

In [6]:
x = X.reshape(4,5) # 5 elements in each row, 4 rows, total elements 4*5 = 20
x

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])

In [11]:
zeros = torch.zeros(2,3,4)
zeros, zeros.shape

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 torch.Size([2, 3, 4]))

In [12]:
ones = torch.ones(2,3,4)
ones, ones.shape

(tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]),
 torch.Size([2, 3, 4]))

In [13]:
randn = torch.randn(3,4)
randn, randn.shape

(tensor([[ 0.6443, -3.2408, -0.3019, -0.1550],
         [ 1.7089, -0.8881, -0.4630, -1.5416],
         [-0.6233,  1.6615, -0.0708, -1.1000]]),
 torch.Size([3, 4]))

In [15]:
X = torch.arange(12, dtype=torch.float32).reshape(3,4)
X[-1], X[0], X[1:], X[1,2], X[:2]

(tensor([ 8.,  9., 10., 11.]),
 tensor([0., 1., 2., 3.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor(6.),
 tensor([[0., 1., 2., 3.],
         [4., 5., 6., 7.]]))

In [17]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
X[0,1]=17
print(X)
X[:2, :] = 12
X

tensor([[ 0., 17.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [18]:
x = torch.tensor([1.0, 2.0, 4.0, 8.0])
y = torch.tensor([2.0, 2.0, 2.0, 2.0])
x+y, x-y, x*y, x/y, x**y, torch.exp(x)

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]),
 tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03]))

In [19]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)

Y = torch.tensor([
    [2.0, 1, 4, 3],
    [1, 2, 3, 4],
    [4, 3, 2, 1]
])

print(torch.cat((X,Y),dim=0)) # (6,4)
print(torch.cat((X,Y),dim=1)) # (3,8)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


In [20]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [21]:
X.sum() # we can produce tensor with methods like arange, or manually providing, operation to reduces a tensor is by using sum method by taking all the elements in that tensore and adding it

tensor(66.)

In [23]:
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)
a,b,a.shape,b.shape,a + b, (a+b).shape

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 torch.Size([3, 1]),
 torch.Size([1, 2]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]),
 torch.Size([3, 2]))

In [26]:
before = id(Y)

Y = Y + X

after = id(Y)
before == after

False

In [28]:
Z = torch.zeros_like(Y)
print(id(Z))
Z[:] = X + Y
print(id(Z))

5190172752
5190172752


In [30]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
A = X.numpy()
B = torch.from_numpy(A)
type(A),type(B), A, B

(numpy.ndarray,
 torch.Tensor,
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=float32),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [32]:
a = torch.tensor([3.5])
a.item(), float(a), int(a)

(3.5, 3.5, 3)